/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jPack_ParqueDiversiones;

/**
 *
 * @author pc
 */
public class jFrame_ParqueDiversiones extends javax.swing.JFrame {
    //Creadndo Objetos (Juegos Mecanicos)
    jClase_JuegoMecanico Carrusel;
    jClase_JuegoMecanico CarrosChocones;
    
    /**
     * Creates new form jFrame_ParqueDiversiones
     */
    public jFrame_ParqueDiversiones() {
        initComponents();
        //Inicializando Objetos
        Carrusel = new jClase_JuegoMecanico();
        CarrosChocones = new jClase_JuegoMecanico();
        //Asignar Valores segun el Juego Mecanico
        
        //Valores Carrusel
        Carrusel.setCapacidad(15);
        Carrusel.setEntrada(5);
        
        //Valores CarrosChocones
        CarrosChocones.setCapacidad(8);
        CarrosChocones.setEntrada(10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jPanel_carrusel = new javax.swing.JPanel();
        jLabel_TipoCarrusel = new javax.swing.JLabel();
        jComboBox_TipoCarrusel = new javax.swing.JComboBox<>();
        jButton_CarruselNuevaVenta = new javax.swing.JButton();
        jButton_CarruselOcupadas = new javax.swing.JButton();
        jButton_CarruselVAciar = new javax.swing.JButton();
        jButton_CarruselIngreso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_CarruselEstadistica = new javax.swing.JButton();
        jPanel_carroschocones = new javax.swing.JPanel();
        jLabel_TipoCarrosChocones = new javax.swing.JLabel();
        jComboBox_TipoCarrosChocones = new javax.swing.JComboBox<>();
        jButton_CarrosNuevaVenta = new javax.swing.JButton();
        jButton_CarrosOcupadas = new javax.swing.JButton();
        jButton_CarrosVAciar = new javax.swing.JButton();
        jButton_CarrosIngreso = new javax.swing.JButton();
        jLabel_CarrosChoconesImg = new javax.swing.JLabel();
        jPanel_carroschocones1 = new javax.swing.JPanel();
        jLabel_TipoCarrosChocones1 = new javax.swing.JLabel();
        jComboBox_TipoMontana = new javax.swing.JComboBox<>();
        jButton_MontanaNuevaVenta = new javax.swing.JButton();
        jButton_CarrosOcupadas1 = new javax.swing.JButton();
        jButton_CarrosVAciar1 = new javax.swing.JButton();
        jButton_CarrosIngreso1 = new javax.swing.JButton();
        jLabel_CarrosChoconesImg1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Titulo_Total_Ingresos = new javax.swing.JLabel();
        jLabel_Titulo_Sillas_Ocupadas = new javax.swing.JLabel();
        jLabel_Titulo_Sillas_VAcias = new javax.swing.JLabel();
        jLabel_Titulo_Porcentaje_Ocupadas = new javax.swing.JLabel();
        jLabel_Titulo_JuegoMasRecaudado = new javax.swing.JLabel();
        jLabel_TotalIngresos = new javax.swing.JLabel();
        jButton_VerEstadisticas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_titulo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel_titulo.setText("Popy Play");

        jPanel_carrusel.setBackground(new java.awt.Color(255, 255, 204));
        jPanel_carrusel.setBorder(javax.swing.BorderFactory.createTitledBorder("CARRUSEL"));

        jLabel_TipoCarrusel.setText("Tipo Carrusel");

        jComboBox_TipoCarrusel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "clasico", "caballos", "tasitas", " " }));
        jComboBox_TipoCarrusel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TipoCarruselActionPerformed(evt);
            }
        });

        jButton_CarruselNuevaVenta.setText("Nueva Venta");
        jButton_CarruselNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CarruselNuevaVentaActionPerformed(evt);
            }
        });

        jButton_CarruselOcupadas.setText("Carrusel Ocupadas");

        jButton_CarruselVAciar.setText("Vaciar");

        jButton_CarruselIngreso.setText("Ingreso");

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\hacktools\\src\\img\\avatar.png")); // NOI18N

        jButton_CarruselEstadistica.setText("Estadistica");

        javax.swing.GroupLayout jPanel_carruselLayout = new javax.swing.GroupLayout(jPanel_carrusel);
        jPanel_carrusel.setLayout(jPanel_carruselLayout);
        jPanel_carruselLayout.setHorizontalGroup(
            jPanel_carruselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_carruselLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_carruselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_carruselLayout.createSequentialGroup()
                        .addGroup(jPanel_carruselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_CarruselOcupadas)
                            .addComponent(jButton_CarruselNuevaVenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_carruselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_carruselLayout.createSequentialGroup()
                                .addComponent(jButton_CarruselVAciar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_CarruselEstadistica))
                            .addComponent(jButton_CarruselIngreso)))
                    .addGroup(jPanel_carruselLayout.createSequentialGroup()
                        .addComponent(jLabel_TipoCarrusel)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_TipoCarrusel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_carruselLayout.setVerticalGroup(
            jPanel_carruselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_carruselLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_carruselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_carruselLayout.createSequentialGroup()
                        .addGroup(jPanel_carruselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_TipoCarrusel)
                            .addComponent(jComboBox_TipoCarrusel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel_carruselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_CarruselNuevaVenta)
                            .addComponent(jButton_CarruselVAciar)
                            .addComponent(jButton_CarruselEstadistica))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_carruselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_CarruselOcupadas)
                            .addComponent(jButton_CarruselIngreso))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel_carroschocones.setBackground(new java.awt.Color(102, 153, 255));
        jPanel_carroschocones.setBorder(javax.swing.BorderFactory.createTitledBorder("CARROS CHOCONES"));

        jLabel_TipoCarrosChocones.setText("Tipo");

        jComboBox_TipoCarrosChocones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "clasico", "caballos", "tasitas", " " }));

        jButton_CarrosNuevaVenta.setText("Nueva Venta");

        jButton_CarrosOcupadas.setText("Carrusel Ocupadas");

        jButton_CarrosVAciar.setText("Vaciar");

        jButton_CarrosIngreso.setText("Ingreso");

        jLabel_CarrosChoconesImg.setIcon(new javax.swing.ImageIcon("G:\\hacktools\\src\\img\\avatar.png")); // NOI18N

        javax.swing.GroupLayout jPanel_carroschoconesLayout = new javax.swing.GroupLayout(jPanel_carroschocones);
        jPanel_carroschocones.setLayout(jPanel_carroschoconesLayout);
        jPanel_carroschoconesLayout.setHorizontalGroup(
            jPanel_carroschoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_carroschoconesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_carroschoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_carroschoconesLayout.createSequentialGroup()
                        .addComponent(jLabel_TipoCarrosChocones)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_TipoCarrosChocones, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_carroschoconesLayout.createSequentialGroup()
                        .addGroup(jPanel_carroschoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_CarrosOcupadas)
                            .addComponent(jButton_CarrosNuevaVenta))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_carroschoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_CarrosVAciar)
                            .addComponent(jButton_CarrosIngreso))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_CarrosChoconesImg, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel_carroschoconesLayout.setVerticalGroup(
            jPanel_carroschoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_carroschoconesLayout.createSequentialGroup()
                .addGroup(jPanel_carroschoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_carroschoconesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_carroschoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_TipoCarrosChocones)
                            .addComponent(jComboBox_TipoCarrosChocones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel_carroschoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_CarrosNuevaVenta)
                            .addComponent(jButton_CarrosVAciar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_carroschoconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_CarrosOcupadas)
                            .addComponent(jButton_CarrosIngreso)))
                    .addGroup(jPanel_carroschoconesLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel_CarrosChoconesImg, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_carroschocones1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel_carroschocones1.setBorder(javax.swing.BorderFactory.createTitledBorder("MONTAÑA RUSA"));

        jLabel_TipoCarrosChocones1.setText("Tipo");

        jComboBox_TipoMontana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "clasico", "caballos", "tasitas", " " }));

        jButton_MontanaNuevaVenta.setText("Nueva Venta");

        jButton_CarrosOcupadas1.setText("Carrusel Ocupadas");

        jButton_CarrosVAciar1.setText("Vaciar");

        jButton_CarrosIngreso1.setText("Ingreso");

        jLabel_CarrosChoconesImg1.setIcon(new javax.swing.ImageIcon("G:\\hacktools\\src\\img\\avatar.png")); // NOI18N

        javax.swing.GroupLayout jPanel_carroschocones1Layout = new javax.swing.GroupLayout(jPanel_carroschocones1);
        jPanel_carroschocones1.setLayout(jPanel_carroschocones1Layout);
        jPanel_carroschocones1Layout.setHorizontalGroup(
            jPanel_carroschocones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_carroschocones1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_carroschocones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_carroschocones1Layout.createSequentialGroup()
                        .addComponent(jLabel_TipoCarrosChocones1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_TipoMontana, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_carroschocones1Layout.createSequentialGroup()
                        .addGroup(jPanel_carroschocones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_CarrosOcupadas1)
                            .addComponent(jButton_MontanaNuevaVenta))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_carroschocones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_CarrosVAciar1)
                            .addComponent(jButton_CarrosIngreso1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_CarrosChoconesImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel_carroschocones1Layout.setVerticalGroup(
            jPanel_carroschocones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_carroschocones1Layout.createSequentialGroup()
                .addGroup(jPanel_carroschocones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_carroschocones1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_carroschocones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_TipoCarrosChocones1)
                            .addComponent(jComboBox_TipoMontana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel_carroschocones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_MontanaNuevaVenta)
                            .addComponent(jButton_CarrosVAciar1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_carroschocones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_CarrosOcupadas1)
                            .addComponent(jButton_CarrosIngreso1)))
                    .addGroup(jPanel_carroschocones1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel_CarrosChoconesImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estadisticas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 3, 24))); // NOI18N

        jLabel_Titulo_Total_Ingresos.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel_Titulo_Total_Ingresos.setText("Total Ingresos");

        jLabel_Titulo_Sillas_Ocupadas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Titulo_Sillas_Ocupadas.setText("Titulo Sillas Ocupadas");

        jLabel_Titulo_Sillas_VAcias.setText("Sillas Vacias");

        jLabel_Titulo_Porcentaje_Ocupadas.setText("% Ocupados");

        jLabel_Titulo_JuegoMasRecaudado.setText("Juego Mas Recaudado");

        jLabel_TotalIngresos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton_VerEstadisticas.setText("Ver Estadisticas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Titulo_Total_Ingresos)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel_TotalIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_Titulo_Sillas_Ocupadas)
                            .addComponent(jLabel_Titulo_Sillas_VAcias)
                            .addComponent(jLabel_Titulo_Porcentaje_Ocupadas)
                            .addComponent(jLabel_Titulo_JuegoMasRecaudado)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jButton_VerEstadisticas)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Titulo_Total_Ingresos)
                    .addComponent(jLabel_TotalIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_Titulo_Sillas_Ocupadas)
                .addGap(33, 33, 33)
                .addComponent(jLabel_Titulo_Sillas_VAcias)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Titulo_Porcentaje_Ocupadas)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Titulo_JuegoMasRecaudado)
                .addGap(18, 18, 18)
                .addComponent(jButton_VerEstadisticas)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel_titulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel_carroschocones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_carrusel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_carroschocones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel_titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_carrusel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_carroschocones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel_carroschocones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_TipoCarruselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TipoCarruselActionPerformed
        // TODO add your handling code here:
        String Tipo;
        jComboBox_TipoCarrusel.getSelectedIndex();
    }//GEN-LAST:event_jComboBox_TipoCarruselActionPerformed

    private void jButton_CarruselNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CarruselNuevaVentaActionPerformed
        // TODO add your handling code here:
        Carrusel.EntraUno();
    }//GEN-LAST:event_jButton_CarruselNuevaVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_ParqueDiversiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_ParqueDiversiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_ParqueDiversiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_ParqueDiversiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_ParqueDiversiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CarrosIngreso;
    private javax.swing.JButton jButton_CarrosIngreso1;
    private javax.swing.JButton jButton_CarrosNuevaVenta;
    private javax.swing.JButton jButton_CarrosOcupadas;
    private javax.swing.JButton jButton_CarrosOcupadas1;
    private javax.swing.JButton jButton_CarrosVAciar;
    private javax.swing.JButton jButton_CarrosVAciar1;
    private javax.swing.JButton jButton_CarruselEstadistica;
    private javax.swing.JButton jButton_CarruselIngreso;
    private javax.swing.JButton jButton_CarruselNuevaVenta;
    private javax.swing.JButton jButton_CarruselOcupadas;
    private javax.swing.JButton jButton_CarruselVAciar;
    private javax.swing.JButton jButton_MontanaNuevaVenta;
    private javax.swing.JButton jButton_VerEstadisticas;
    private javax.swing.JComboBox<String> jComboBox_TipoCarrosChocones;
    private javax.swing.JComboBox<String> jComboBox_TipoCarrusel;
    private javax.swing.JComboBox<String> jComboBox_TipoMontana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_CarrosChoconesImg;
    private javax.swing.JLabel jLabel_CarrosChoconesImg1;
    private javax.swing.JLabel jLabel_TipoCarrosChocones;
    private javax.swing.JLabel jLabel_TipoCarrosChocones1;
    private javax.swing.JLabel jLabel_TipoCarrusel;
    private javax.swing.JLabel jLabel_Titulo_JuegoMasRecaudado;
    private javax.swing.JLabel jLabel_Titulo_Porcentaje_Ocupadas;
    private javax.swing.JLabel jLabel_Titulo_Sillas_Ocupadas;
    private javax.swing.JLabel jLabel_Titulo_Sillas_VAcias;
    private javax.swing.JLabel jLabel_Titulo_Total_Ingresos;
    private javax.swing.JLabel jLabel_TotalIngresos;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_carroschocones;
    private javax.swing.JPanel jPanel_carroschocones1;
    private javax.swing.JPanel jPanel_carrusel;
    // End of variables declaration//GEN-END:variables
}
