/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jPack_Pregunta2;

/**
 *
 * @author pc
 */
public class JFrame_triangulos extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_triangulos
     */
    public JFrame_triangulos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_TEscaleno = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_equi_c = new javax.swing.JTextField();
        jTextField_equi_a = new javax.swing.JTextField();
        jTextField_equi_b = new javax.swing.JTextField();
        jLabel_equi_respuesta_area = new javax.swing.JLabel();
        jLabel_equi_respuesta_perimetro = new javax.swing.JLabel();
        jButton_Equilatero = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_equi_altura = new javax.swing.JTextField();
        jTextField_equi_base = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel_TEscaleno2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_TEscaleno_c = new javax.swing.JTextField();
        jTextField_TEscaleno_a = new javax.swing.JTextField();
        jTextField_TEscaleno_b = new javax.swing.JTextField();
        jLabel_TEscaleno_respuesta_area = new javax.swing.JLabel();
        jLabel_TEscaleno_respuesta_perimetro = new javax.swing.JLabel();
        jButton_TEscaleno = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_TEscaleno_altura = new javax.swing.JTextField();
        jTextField_TEscaleno_base = new javax.swing.JTextField();
        jPanel_TEscaleno3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_Iso_c = new javax.swing.JTextField();
        jTextField_iso_a = new javax.swing.JTextField();
        jTextField_iso_b = new javax.swing.JTextField();
        jLabel_iso_respuesta_area = new javax.swing.JLabel();
        jLabel_iso_respuesta_perimetro = new javax.swing.JLabel();
        jButton_Isoseles = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField_iso_altura = new javax.swing.JTextField();
        jTextField_iso_base = new javax.swing.JTextField();
        jPanel_TEscaleno4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField_Recto_c = new javax.swing.JTextField();
        jTextField_TRecto_a = new javax.swing.JTextField();
        jTextField_Recto_b = new javax.swing.JTextField();
        jLabel_Recto_respuesta_area = new javax.swing.JLabel();
        jLabel_Recto_respuesta_perimetro = new javax.swing.JLabel();
        jButton_Recto = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField_Recto_altura = new javax.swing.JTextField();
        jTextField_Recto_base = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_TEscaleno.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Triangulo Equilatero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel_TEscaleno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Valor A:");
        jPanel_TEscaleno.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setText("Valor B:");
        jPanel_TEscaleno.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setText("Valor C:");
        jPanel_TEscaleno.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel_TEscaleno.add(jTextField_equi_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 50, -1));
        jPanel_TEscaleno.add(jTextField_equi_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 50, -1));
        jPanel_TEscaleno.add(jTextField_equi_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 50, -1));

        jLabel_equi_respuesta_area.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Area"));
        jPanel_TEscaleno.add(jLabel_equi_respuesta_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 190, 40));

        jLabel_equi_respuesta_perimetro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Perimetro"));
        jPanel_TEscaleno.add(jLabel_equi_respuesta_perimetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 190, 40));

        jButton_Equilatero.setText("Calular");
        jButton_Equilatero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EquilateroActionPerformed(evt);
            }
        });
        jPanel_TEscaleno.add(jButton_Equilatero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 30));

        jLabel5.setText("Base:");
        jPanel_TEscaleno.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel6.setText("Altura:");
        jPanel_TEscaleno.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));
        jPanel_TEscaleno.add(jTextField_equi_altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 100, -1));
        jPanel_TEscaleno.add(jTextField_equi_base, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 100, -1));

        getContentPane().add(jPanel_TEscaleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 380, 180));

        jLabel2.setText("TRIANGULOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jPanel_TEscaleno2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Triangulo Escaleno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel_TEscaleno2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Valor A:");
        jPanel_TEscaleno2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel8.setText("Valor B:");
        jPanel_TEscaleno2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel9.setText("Valor C:");
        jPanel_TEscaleno2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel_TEscaleno2.add(jTextField_TEscaleno_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 50, -1));
        jPanel_TEscaleno2.add(jTextField_TEscaleno_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 50, -1));
        jPanel_TEscaleno2.add(jTextField_TEscaleno_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 50, -1));

        jLabel_TEscaleno_respuesta_area.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Area"));
        jPanel_TEscaleno2.add(jLabel_TEscaleno_respuesta_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 190, 40));

        jLabel_TEscaleno_respuesta_perimetro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Perimetro"));
        jPanel_TEscaleno2.add(jLabel_TEscaleno_respuesta_perimetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 190, 40));

        jButton_TEscaleno.setText("Calular");
        jButton_TEscaleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TEscalenoActionPerformed(evt);
            }
        });
        jPanel_TEscaleno2.add(jButton_TEscaleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 30));

        jLabel10.setText("Base:");
        jPanel_TEscaleno2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel11.setText("Altura:");
        jPanel_TEscaleno2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));
        jPanel_TEscaleno2.add(jTextField_TEscaleno_altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 100, -1));
        jPanel_TEscaleno2.add(jTextField_TEscaleno_base, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 100, -1));

        getContentPane().add(jPanel_TEscaleno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 380, 180));

        jPanel_TEscaleno3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Triangulo Isoseles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel_TEscaleno3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Valor A:");
        jPanel_TEscaleno3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel13.setText("Valor B:");
        jPanel_TEscaleno3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel14.setText("Valor C:");
        jPanel_TEscaleno3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel_TEscaleno3.add(jTextField_Iso_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 50, -1));
        jPanel_TEscaleno3.add(jTextField_iso_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 50, -1));
        jPanel_TEscaleno3.add(jTextField_iso_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 50, -1));

        jLabel_iso_respuesta_area.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Area"));
        jPanel_TEscaleno3.add(jLabel_iso_respuesta_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 190, 40));

        jLabel_iso_respuesta_perimetro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Perimetro"));
        jPanel_TEscaleno3.add(jLabel_iso_respuesta_perimetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 190, 40));

        jButton_Isoseles.setText("Calular");
        jButton_Isoseles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IsoselesActionPerformed(evt);
            }
        });
        jPanel_TEscaleno3.add(jButton_Isoseles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 30));

        jLabel15.setText("Base:");
        jPanel_TEscaleno3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel16.setText("Altura:");
        jPanel_TEscaleno3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));
        jPanel_TEscaleno3.add(jTextField_iso_altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 100, -1));
        jPanel_TEscaleno3.add(jTextField_iso_base, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 100, -1));

        getContentPane().add(jPanel_TEscaleno3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 380, 180));

        jPanel_TEscaleno4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Triangulo Recto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel_TEscaleno4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Valor A:");
        jPanel_TEscaleno4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel18.setText("Valor B:");
        jPanel_TEscaleno4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel19.setText("Valor C:");
        jPanel_TEscaleno4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel_TEscaleno4.add(jTextField_Recto_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 50, -1));
        jPanel_TEscaleno4.add(jTextField_TRecto_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 50, -1));
        jPanel_TEscaleno4.add(jTextField_Recto_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 50, -1));

        jLabel_Recto_respuesta_area.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Area"));
        jPanel_TEscaleno4.add(jLabel_Recto_respuesta_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 190, 40));

        jLabel_Recto_respuesta_perimetro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Perimetro"));
        jPanel_TEscaleno4.add(jLabel_Recto_respuesta_perimetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 190, 40));

        jButton_Recto.setText("Calular");
        jButton_Recto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RectoActionPerformed(evt);
            }
        });
        jPanel_TEscaleno4.add(jButton_Recto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 30));

        jLabel20.setText("Base:");
        jPanel_TEscaleno4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel21.setText("Altura:");
        jPanel_TEscaleno4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));
        jPanel_TEscaleno4.add(jTextField_Recto_altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 100, -1));
        jPanel_TEscaleno4.add(jTextField_Recto_base, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 100, -1));

        getContentPane().add(jPanel_TEscaleno4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 380, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_EquilateroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EquilateroActionPerformed
        // Triangulo Escaleno:
        //Mensjaes
        String area,perimetro = "";
        //TEscaleno Escaleno = new TEscaleno();
        int a= Integer.parseInt(jTextField_equi_a.getText());
        int altura= Integer.parseInt(jTextField_equi_altura.getText());
        int b= Integer.parseInt(jTextField_equi_b.getText());
        int base= Integer.parseInt(jTextField_equi_base.getText());
        int c= Integer.parseInt(jTextField_equi_c.getText());
        
        //area 
        area = "Area es:"+(base* altura)/2;
        
        //preimetro
        perimetro = "Perimetro es: " + (a+b+c);
        
        //Mostrando respuesta:
        jLabel_equi_respuesta_area.setText(area);
        jLabel_equi_respuesta_perimetro.setText(perimetro);
    }//GEN-LAST:event_jButton_EquilateroActionPerformed

    private void jButton_TEscalenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TEscalenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_TEscalenoActionPerformed

    private void jButton_IsoselesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IsoselesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_IsoselesActionPerformed

    private void jButton_RectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RectoActionPerformed
        // Triangulo Escaleno:
        //Mensjaes
        String area,perimetro = "";
        //TEscaleno Escaleno = new TEscaleno();
        int a= Integer.parseInt(jTextField_equi_a.getText());
        int altura= Integer.parseInt(jTextField_equi_altura.getText());
        int b= Integer.parseInt(jTextField_equi_b.getText());
        int base= Integer.parseInt(jTextField_equi_base.getText());
        int c= Integer.parseInt(jTextField_equi_c.getText());
        
        //area 
        area = "Area es:"+(base* altura)/2;
        
        //preimetro
        perimetro = "Perimetro es: " + (a+b+c);
        
        //Mostrando respuesta:
        jLabel_equi_respuesta_area.setText(area);
        jLabel_equi_respuesta_perimetro.setText(perimetro);
    }//GEN-LAST:event_jButton_RectoActionPerformed
                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_triangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_triangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_triangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_triangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_triangulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Equilatero;
    private javax.swing.JButton jButton_Isoseles;
    private javax.swing.JButton jButton_Recto;
    private javax.swing.JButton jButton_TEscaleno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Recto_respuesta_area;
    private javax.swing.JLabel jLabel_Recto_respuesta_perimetro;
    private javax.swing.JLabel jLabel_TEscaleno_respuesta_area;
    private javax.swing.JLabel jLabel_TEscaleno_respuesta_perimetro;
    private javax.swing.JLabel jLabel_equi_respuesta_area;
    private javax.swing.JLabel jLabel_equi_respuesta_perimetro;
    private javax.swing.JLabel jLabel_iso_respuesta_area;
    private javax.swing.JLabel jLabel_iso_respuesta_perimetro;
    private javax.swing.JPanel jPanel_TEscaleno;
    private javax.swing.JPanel jPanel_TEscaleno2;
    private javax.swing.JPanel jPanel_TEscaleno3;
    private javax.swing.JPanel jPanel_TEscaleno4;
    private javax.swing.JTextField jTextField_Iso_c;
    private javax.swing.JTextField jTextField_Recto_altura;
    private javax.swing.JTextField jTextField_Recto_b;
    private javax.swing.JTextField jTextField_Recto_base;
    private javax.swing.JTextField jTextField_Recto_c;
    private javax.swing.JTextField jTextField_TEscaleno_a;
    private javax.swing.JTextField jTextField_TEscaleno_altura;
    private javax.swing.JTextField jTextField_TEscaleno_b;
    private javax.swing.JTextField jTextField_TEscaleno_base;
    private javax.swing.JTextField jTextField_TEscaleno_c;
    private javax.swing.JTextField jTextField_TRecto_a;
    private javax.swing.JTextField jTextField_equi_a;
    private javax.swing.JTextField jTextField_equi_altura;
    private javax.swing.JTextField jTextField_equi_b;
    private javax.swing.JTextField jTextField_equi_base;
    private javax.swing.JTextField jTextField_equi_c;
    private javax.swing.JTextField jTextField_iso_a;
    private javax.swing.JTextField jTextField_iso_altura;
    private javax.swing.JTextField jTextField_iso_b;
    private javax.swing.JTextField jTextField_iso_base;
    // End of variables declaration//GEN-END:variables
}
