/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jPack_MiCollague2022;

/**
 *
 * @author pc
 */
public class jFrame_MisCollague extends javax.swing.JFrame {

    /**
     * Creates new form jFrame_MisCollague
     */
    public jFrame_MisCollague() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane_PanelInterno = new javax.swing.JDesktopPane();
        jMenuBar_collague = new javax.swing.JMenuBar();
        jMenu_archivos = new javax.swing.JMenu();
        jMenuItem_abrir = new javax.swing.JMenuItem();
        jMenuItem_cerrar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_salir = new javax.swing.JMenuItem();
        jMenu_Salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane_PanelInternoLayout = new javax.swing.GroupLayout(jDesktopPane_PanelInterno);
        jDesktopPane_PanelInterno.setLayout(jDesktopPane_PanelInternoLayout);
        jDesktopPane_PanelInternoLayout.setHorizontalGroup(
            jDesktopPane_PanelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
        );
        jDesktopPane_PanelInternoLayout.setVerticalGroup(
            jDesktopPane_PanelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane_PanelInterno, java.awt.BorderLayout.CENTER);

        jMenu_archivos.setText("Archivo");

        jMenuItem_abrir.setText("Abrir");
        jMenu_archivos.add(jMenuItem_abrir);

        jMenuItem_cerrar.setText("Cerrar");
        jMenu_archivos.add(jMenuItem_cerrar);
        jMenu_archivos.add(jSeparator1);

        jMenuItem_salir.setText("Salir");
        jMenu_archivos.add(jMenuItem_salir);

        jMenuBar_collague.add(jMenu_archivos);

        jMenu_Salir.setText("Salir");
        jMenuBar_collague.add(jMenu_Salir);

        setJMenuBar(jMenuBar_collague);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_MisCollague.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_MisCollague.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_MisCollague.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_MisCollague.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_MisCollague().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane_PanelInterno;
    private javax.swing.JMenuBar jMenuBar_collague;
    private javax.swing.JMenuItem jMenuItem_abrir;
    private javax.swing.JMenuItem jMenuItem_cerrar;
    private javax.swing.JMenuItem jMenuItem_salir;
    private javax.swing.JMenu jMenu_Salir;
    private javax.swing.JMenu jMenu_archivos;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
