/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jPack_AbirGuardar;

import static java.time.Clock.system;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;

/**
 *
 * @author pc
 */
public class jFrame_AbrirGuardar extends javax.swing.JFrame {

    /**
     * Creates new form jFrame_AbrirGuardar
     */
    public jFrame_AbrirGuardar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser_seleccionarArchivo = new javax.swing.JFileChooser();
        jToolBar_Iconos = new javax.swing.JToolBar();
        jButton_uno = new javax.swing.JButton();
        jButton_cuatro = new javax.swing.JButton();
        jButton_dos = new javax.swing.JButton();
        jButton_tres = new javax.swing.JButton();
        jButton_cinco = new javax.swing.JButton();
        jMenuBar_principal = new javax.swing.JMenuBar();
        jMenu_archivo = new javax.swing.JMenu();
        jMenuItem_abrir = new javax.swing.JMenuItem();
        jMenuItem_guardar = new javax.swing.JMenuItem();
        jSeparator_archivo = new javax.swing.JPopupMenu.Separator();
        jMenuItem_salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar_Iconos.setRollover(true);

        jButton_uno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_img/8666724_upload_icon.png"))); // NOI18N
        jButton_uno.setFocusable(false);
        jButton_uno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_uno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_unoActionPerformed(evt);
            }
        });
        jToolBar_Iconos.add(jButton_uno);

        jButton_cuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_img/8666542_save_icon.png"))); // NOI18N
        jButton_cuatro.setFocusable(false);
        jButton_cuatro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_cuatro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cuatroActionPerformed(evt);
            }
        });
        jToolBar_Iconos.add(jButton_cuatro);

        jButton_dos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_img/8666595_x_icon.png"))); // NOI18N
        jButton_dos.setFocusable(false);
        jButton_dos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_dos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dosActionPerformed(evt);
            }
        });
        jToolBar_Iconos.add(jButton_dos);

        jButton_tres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_img/8666784_box_package_delivery_icon.png"))); // NOI18N
        jButton_tres.setFocusable(false);
        jButton_tres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_tres.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tresActionPerformed(evt);
            }
        });
        jToolBar_Iconos.add(jButton_tres);

        jButton_cinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jPack_img/8666616_shopping_cart_icon.png"))); // NOI18N
        jButton_cinco.setFocusable(false);
        jButton_cinco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_cinco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cincoActionPerformed(evt);
            }
        });
        jToolBar_Iconos.add(jButton_cinco);

        jMenu_archivo.setText("Archivo");

        jMenuItem_abrir.setText("Abrir");
        jMenuItem_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_abrirActionPerformed(evt);
            }
        });
        jMenu_archivo.add(jMenuItem_abrir);

        jMenuItem_guardar.setText("Guardar");
        jMenuItem_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_guardarActionPerformed(evt);
            }
        });
        jMenu_archivo.add(jMenuItem_guardar);
        jMenu_archivo.add(jSeparator_archivo);

        jMenuItem_salir.setText("Salir");
        jMenu_archivo.add(jMenuItem_salir);

        jMenuBar_principal.add(jMenu_archivo);

        jMenu2.setText("Edit");
        jMenuBar_principal.add(jMenu2);

        setJMenuBar(jMenuBar_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar_Iconos, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar_Iconos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 382, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_abrirActionPerformed
        // variable auxiliar:
        //
        int respuesta ;
        respuesta = jFileChooser_seleccionarArchivo.showOpenDialog(this);
        
        //Para JFileChooser usar la libreria import javax.swing.JFileChooser;
        if(respuesta == JFileChooser.APPROVE_OPTION){
            //
            JOptionPane.showMessageDialog(null,jFileChooser_seleccionarArchivo.getSelectedFile().toString());
            
        }else{
            if(respuesta == JFileChooser.CANCEL_OPTION){
                 JOptionPane.showMessageDialog(null,"Se cancelo");
            }
        }
                
        
    }//GEN-LAST:event_jMenuItem_abrirActionPerformed

    private void jMenuItem_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_guardarActionPerformed
        // variable auxiliar:
        int res ;
        res = jFileChooser_seleccionarArchivo.showSaveDialog(this);
        
        if(res == JFileChooser.APPROVE_OPTION){
            JOptionPane.showMessageDialog(null,jFileChooser_seleccionarArchivo.getSelectedFile());
            
        }else{
            if(res == JFileChooser.CANCEL_OPTION){
                 JOptionPane.showMessageDialog(null,"Se cancelo");
            }
        }
    }//GEN-LAST:event_jMenuItem_guardarActionPerformed

    private void jButton_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_unoActionPerformed
        // TODO add your handling code here:
        int respuesta ;
        respuesta = jFileChooser_seleccionarArchivo.showOpenDialog(this);
        
        //Para JFileChooser usar la libreria import javax.swing.JFileChooser;
        if(respuesta == JFileChooser.APPROVE_OPTION){
            //
            JOptionPane.showMessageDialog(null,jFileChooser_seleccionarArchivo.getSelectedFile().toString());
            
        }else{
            if(respuesta == JFileChooser.CANCEL_OPTION){
                 JOptionPane.showMessageDialog(null,"Se cancelo");
            }
        }
    }//GEN-LAST:event_jButton_unoActionPerformed

    private void jButton_cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cuatroActionPerformed
        // TODO add your handling code here:
        // variable auxiliar:
        int res ;
        res = jFileChooser_seleccionarArchivo.showSaveDialog(this);
        
        if(res == JFileChooser.APPROVE_OPTION){
            JOptionPane.showMessageDialog(null,jFileChooser_seleccionarArchivo.getSelectedFile());
            
        }else{
            if(res == JFileChooser.CANCEL_OPTION){
                 JOptionPane.showMessageDialog(null,"Se cancelo");
            }
        }
    }//GEN-LAST:event_jButton_cuatroActionPerformed

    private void jButton_dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dosActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_dosActionPerformed

    private void jButton_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tresActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Icono Seleccionar Componentes");
    }//GEN-LAST:event_jButton_tresActionPerformed

    private void jButton_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cincoActionPerformed
        // TODO add your handling code here:
       JOptionPane.showMessageDialog(null, "Icono comprar");
    }//GEN-LAST:event_jButton_cincoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_AbrirGuardar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_AbrirGuardar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_AbrirGuardar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_AbrirGuardar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_AbrirGuardar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cinco;
    private javax.swing.JButton jButton_cuatro;
    private javax.swing.JButton jButton_dos;
    private javax.swing.JButton jButton_tres;
    private javax.swing.JButton jButton_uno;
    private javax.swing.JFileChooser jFileChooser_seleccionarArchivo;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar_principal;
    private javax.swing.JMenuItem jMenuItem_abrir;
    private javax.swing.JMenuItem jMenuItem_guardar;
    private javax.swing.JMenuItem jMenuItem_salir;
    private javax.swing.JMenu jMenu_archivo;
    private javax.swing.JPopupMenu.Separator jSeparator_archivo;
    private javax.swing.JToolBar jToolBar_Iconos;
    // End of variables declaration//GEN-END:variables
}
